---
- hosts: all
  remote_user: root
  roles:
   - common

- hosts: lbservers
  remote_user: root
  roles:
   - nginxlb

- hosts: webservers
  remote_user: root
  roles:
   - apacheweb

- hosts: lbservers
  remote_user: root
  roles:
   - ha
