- name: Installation Nginx Server LBC
  yum:
   name: nginx
   state: latest
- name: Gen Nginx Config file
  copy:
   src: nginx.conf
   dest: /etc/nginx/nginx.conf
  tags:
   - nginxconf
  notify:
   - restart nginx
- name:
  service:
   name: nginx
   enabled: true
   state: started
